import { Inter } from "next/font/google";
import "./globals.css";
import { ButtonTodo } from "@/components/button";
import { jost } from "@/utils/fonts";
import Link from "next/link";
import { DeleteAllTodos } from "@/utils/fetch";
import { useStore } from "@/utils/storeZustand";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  if (useStore.getState().deleteAllTodosState) {
    DeleteAllTodos();
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full h-full bg-gray-900 text-white`}
      >
        <header className="mt-10">
          <div className="w-max mx-auto flex flex-col items-center justify-center">
            <Link
              href={"/"}
              className={`text-7xl text-blue-200 ${jost.className}`}
            >
              TODO LIST
            </Link>
            <h3 className={`text-lg text-blue-300 ${jost.className}`}>
              Right-click on cards to edit and delete.
            </h3>
          </div>
          <nav className="mt-12 w-4/5 mx-auto flex justify-between items-center">
            <ButtonTodo type={"addTodo"}>Add ToDo</ButtonTodo>

            <ButtonTodo type={"deleteTodos"}>Delete ALL ToDos</ButtonTodo>
          </nav>
        </header>
        <hr className="mt-10 custom-hr mx-auto" />
        {children}
      </body>
    </html>
  );
}
